[package]
name = "mirror-plugin"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
env_logger.workspace = true
log.workspace = true
chrono.workspace = true