[package]
name = "image-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
image = "0.25"
libloading="0.9"
thiserror.workspace = true
plugins-support={path = "../plugins_support"}
log.workspace = true